AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'Gemfile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/LineLength:
  Max: 100